# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92d1f4c56ecd613648e95b1309cf31a8676745ad8e93b13d7fec64414ccbebb86cba334ed27718ae7be5384b547c4c5879f249365e3367b9f31a270295dc6739

test:
  secret_key_base: f385926bffa58148800fa9ef49179e5b2acffcba485288733bc1298d8ea9e3af766288fc7db4416fd1bc06c7109b90825b02657ad6b11272f9d3a757553c03d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
